pageinfo = [[1216244947,789],
	[1227649827,937],
	[1227649827,2056],
	[1217440465,2885],
	[1228870920,5756],
	[1228870714,64348],
	[1228870907,1997],
	[1228870899,2527],
	[1228870888,775],
	[1216740464,3751],
	[1228870868,1139],
	[1228870875,2926],
	[1228870966,82695],
	[1228870972,23841],
	[1227649828,3280],
	[1216248658,3409],
	[1216248792,2352],
	[1216249153,6318],
	[1216249437,4286],
	[1216249695,4385],
	[1227649828,4740],
	[1216250184,2021],
	[1228871001,6702],
	[1228161135,17873],
	[1228871019,1847],
	[1216315890,6531],
	[1228871018,10496],
	[1228871027,32583],
	[1228871028,6453],
	[1229018478,80182],
	[1227649829,819],
	[1228871068,3559],
	[1229018557,1756],
	[1228871075,3058],
	[1228871083,1831],
	[1228871088,1775],
	[1228871094,1511],
	[1227649829,404],
	[1228178061,12498],
	[1228172137,4480],
	[1228870680,4429],
	[1228172384,11862],
	[1228345550,7344],
	[1227649830,1040],
	[1228871164,1830],
	[1228871168,38212],
	[1228871171,7348],
	[1216674598,22407],
	[1216406171,4601],
	[1228871186,20365],
	[1228871191,14141],
	[1228871116,3467],
	[1227649830,9104],
	[1228871147,1944],
	[1217453830,4231],
	[1227649830,4843],
	[1216416370,4470],
	[1228870671,10046],
	[1229018597,22090],
	[1228871214,2031],
	[1217454128,3501],
	[1228871232,508],
	[1228871239,1309],
	[1228871243,10367],
	[1228846356,20890],
	[1217453892,670],
	[1227649831,4331],
	[1228869857,3395],
	[1227649831,1048],
	[1227649831,16787],
	[1216244954,2968],
	[1216244954,3771],
	[1216244954,3442],
	[1217453848,1684]];
pagedata = [ ["about.htm","About","Cisco Networking Academy is a comprehensive e-learning initiative that enables students to develop valuable information and communication technolo...",""],
["about2.htm","About","Using the Help Files The help files are designed to familiarize users with the Packet Tracer 5.1 interface, functions, and features. Although the ...",""],
["acknowledgements.htm","Acknowledgements","Packet Tracer Development Packet Tracer Concept and Design Dennis Frezzo Michael Wang Mark Chen Brad Anderson Packet Tracer 5.1 Team Project Manag...",""],
["activityWizard.htm","Activity Wizard","Activity Wizard The Activity Wizard is an assessment tool that allows you to create highly specific networking scenarios for other users. This too...",""],
["activityWizard_answerNetwork.htm","Answer Network","Answer Network In the Answer Network panel, you construct the answer network, and mark the elements of the network on which you want to assess the...",""],
["activityWizard_assessmentItems.htm","Assessment Items","?Assessment Items What are Assessment Items? The assessment items are found in the Assessment Items tab of the Answer Network section in the Activ...",""],
["activityWizard_initialNetwork.htm","Initial Network","Initial Network In the Initial Network panel, you set the network from which the user will start the activity. One option for setting up the initi...",""],
["activityWizard_instructions.htm","Instructions","Instructions The student instructions for the activity are entered in the Instructions panel. When students open the activity file, the instructio...",""],
["activityWizard_password.htm","Password","Password The Password Options panel allows you to set a password for the Activity Wizard features of the activity file. If no password is set, any...",""],
["activityWizard_run.htm","Running Activity Files","Running Activity Files You start an activity by opening a saved activity (.pka) file. You will first see the Instructions window telling you how t...",""],
["activityWizard_test.htm","Testing/Checking the Activity (Previewing)","Testing/Checking the Activity (Previewing) When you choose the Test Activity tab from the Activity Menu, you can do a trial run of the activity yo...",""],
["activityWizard_variableManager.htm","Variable Manager","Variable Manager In the Variable Manager panel , you will be able to add dynamism to activities. Numbers, strings, and IP addresses may be assigne...",""],
["CLI_routerIOS.htm","Cisco IOS Supported Commands: Routers","Routers: IOS Packet Tracer 5.1 uses a simplified model of the Cisco IOS. Click on the CLI tab in the router configuration window to access the Cis...",""],
["CLI_switchIOS.htm","Cisco IOS Supported Commands: Switches","Switches: IOS Packet Tracer 5.1 uses a simplified model of the Cisco IOS. Click on the CLI tab in the switch configuration window to access the Ci...",""],
["configuringDevices.htm","Configuring Devices","Configuring Devices As with real networks, the networks you make in Packet Tracer 5.1 must be properly configured before they \"work.\" For simple d...",""],
["config_clouds.htm","Configuring Clouds","Configuring Clouds The Config tab offers three general levels of configuration: global, connections, and interface. To configure at the global lev...",""],
["config_others.htm","Configuring Other Devices","Configuring Other Devices The configuration options for all other devices are relatively simple. In general, you can change their display names in...",""],
["config_PCs.htm","Configuring PCs","Configuring PCs You can configure the global settings and interface settings on the PC with the Config tab. Additionally, the Desktop tab provides...",""],
["config_routers.htm","Configuring Routers","Configuring Routers The Config tab offers four general levels of configuration: global, routing, switching (Cisco 1841 and Cisco 2811 only), and i...",""],
["config_servers.htm","Configuring Servers","Configuring Servers The Config tab offers three general levels of configuration: global, services, and interface. To configure at the global level...",""],
["config_switches.htm","Configuring Switches","Configuring Switches The Config tab for the switch offers three general levels of configuration: global, switching, and interface. The global leve...",""],
["config_wrt300n.htm","Configuring Linksys WRT300N","Configuring Linksys WRT300N The Config tab offers two general levels of configuration: global and interface. To configure at the global level, pre...",""],
["connectionsLinks.htm","Connections / Links","Connections / Links Packet Tracer 5.1 supports a wide range of network connections. Each cable type can only be connected to certain interface typ...",""],
["copyrights.htm","Copyrights","Cisco Networking Academy Packet Tracer (5.1) Software License Agreement IMPORTANT: PLEASE READ THIS PACKET TRACER SOFTWARE LICENSE AGREEMENT (THE ...",""],
["devicesAndModules.htm","Devices and Modules","Devices and Modules Packet Tracer 5.1 supports a wide array of modules for networking devices. Note that you need to turn off a device before addi...",""],
["devicesAndModules_endDevices.htm","Devices and Modules: End Devices","Devices and Modules: End Devices All images on this page are thumbnails in which you can click to bring up a larger image. PC-PT The PC-PT provide...",""],
["devicesAndModules_others.htm","Devices and Modules: Other Devices","Devices and Modules: Other Devices All images on this page are thumbnails on which you can click to bring up a larger image. Hub-PT The Hub-PT pro...",""],
["devicesAndModules_routers.htm","Devices and Modules: Routers","Devices and Modules: Routers All images on this page are thumbnails on which you can click to bring up a larger image. Router: 1841 The Cisco 1841...",""],
["devicesAndModules_switches.htm","Devices and Modules: Switches","Devices and Modules: Switches All images on this page are thumbnails on which you can click to bring up a larger image. Switch: 2950-24 The Cisco ...",""],
["faqTroubleShoot.htm","Frequently Asked Questions (FAQ)/Troubleshoot Guide","Frequently Asked Questions (FAQ)/Troubleshooting Guide General Issues 1. My computer frequently crashes when I use Packet Tracer 5.1. 2. The progr...",""],
["gettingStarted.htm","Getting Started","Getting Started The best place to get started is to review the help files. The help files contain comprehensive documentation on almost all the fe...",""],
["GUI_wrt300n.htm","Linksys WRT300N: GUI","Linksys WRT300N: GUI The GUI tab offers the same configurations and settings as the Config tab with some additional features for port forwarding, ...",""],
["includedSaveFiles.htm","Included Save Files","Included Save Files The SAVES directory of Packet Tracer contains sample network files. REFERENCE TOPOLOGIES: These starter topologies were used f...",""],
["includedSaveFiles_conceptBuilder.htm","Concept Builders","Concept Builders Concept builders are model-building inquiries and investigations leading to student-created explanations and animations of networ...",""],
["includedSaveFiles_design.htm","Design Challenges","Design Challenges Design challenges are constraint-based problems with multiple correct solutions. They may range from very simple (devise a class...",""],
["includedSaveFiles_skillBuilder.htm","Skill Builders","Skill Builders Skill builders support algorithmic problem solving in support of the development of networking procedural knowledge. For example, s...",""],
["includedSaveFiles_troubleshoot.htm","Troubleshooting","Troubleshooting Troubleshooting activities include diagnosing, isolating, and fixing the simulated network from a previously bugged network file. ...",""],
["index.htm","Packet Tracer 5.1 Help","",""],
["interfaceOverview.htm","Interface Overview","Interface Overview When you open Packet Tracer 5.1, by default you will be presented with the following interface: This initial interface contains...",""],
["intro.htm","Introduction","Introduction Welcome to Packet Tracer 5.1. Packet Tracer 5.1 is a standalone, medium-fidelity, simulation-based learning environment for networkin...",""],
["ipc.htm","IPC","IPC (Inter-Process Communication) The IPC (Inter-Process Communication) feature controls an external programming extension for Packet Tracer 5.1 t...",""],
["keyboardShortcuts.htm","Keyboard Shortcuts","Keyboard Shortcuts Many actions in Packet Tracer 5.1 are keyboard-accessible for your convenience. In addition to key combinations, the following ...",""],
["menu.htm","Main Menu","Packet Tracer 5.1 Search Introduction What&#39;s New Program Usage Getting Started Interface Overview My First PT Lab Tutorials Workspace Basics Logic...",""],
["modeling.htm","Modeling in Packet Tracer 5.1","Modeling in Packet Tracer 5.1 Packet Tracer 5.1 simulates the behavior of real networks and devices using models. As with all simulations, the pro...",""],
["model_layer1.htm","Layer 1 Models","Layer 1 Models How hubs process frames When a hub receives a frame ( flowchart here): If two or more ports receive frames at the same time, a coll...",""],
["model_layer2.htm","Layer 2 Models","Layer 2 Models How switches process incoming frames When a switch receives a frame ( flowchart here): It compares the receiving port&#39;s type (trunk...",""],
["model_layer3IP.htm","Layer 3 IP Models","Layer 3 IP Models How IP and IPv6 are modeled Packet Tracer 5.1 models only certain aspects of IP. IP version 4 is modeled. IP addresses are 32 bi...",""],
["model_layer3Routing.htm","Layer 3 Routing Models","Layer 3 Routing Models - RIPv1 RIPv2 EIGRP OSPF How a router starts the RIP process The router generates a RIP request packet to be sent out all p...",""],
["model_layer4.htm","Layer 4 Models","Layer 4 Models How devices process UDP segments This procedure explains how a device sends and receives UDP segments. When the device receives a s...",""],
["model_layer7.htm","Layer 7 Models","Layer 7 Models How DHCP clients process incoming packets When a DHCP client device receives a packet: It drops the packet if (any): The packet is ...",""],
["model_misc.htm","Other Models","Other Models How routers process incoming packets (NAT process) When a router receives a packet: It checks if the receiving port is a NAT outside ...",""],
["mode_realtime.htm","Realtime Mode","Realtime Mode In Realtime Mode, your network is always running (like a real network) whether you are working on the network or not. Your configura...",""],
["mode_simulation.htm","Simulation Mode","Simulation Mode In Simulation Mode, you can watch your network run at a slower pace, observing the paths that packets take and inspecting them in ...",""],
["mode_simulation_complexPDUs.htm","Simulation Mode: Complex PDUs","Simulation Mode: Complex PDUs In addition to simple, quick pings, you can also send customized PDUs. In the Common Tools Bar, press the Add Comple...",""],
["mode_simulation_PDUinfo.htm","Simulation Mode: PDU Information","Simulation Mode: PDU Information During a simulation, you can click on a packet (on the topology or the corresponding event in the Event List) to ...",""],
["mode_simulation_Scenarios.htm","Simulation Mode: Managing Simulation Scenarios","Simulation Mode: Managing Simulation Scenarios In Packet Tracer 5.1, you can set up and simulate complex networking situations (scenarios) through...",""],
["mode_simulation_specialNotes.htm","Simulation Mode: Special Notes","Simulation Mode: Special Notes Editing the Network and Using the Cisco IOS in Simulation Mode Although Realtime Mode is the preferred mode for net...",""],
["multiuser.htm","Multiuser","Multiuser Multiuser is allows communication between one instance of Packet Tracer to another instance. By allowing communication between Packet Tr...",""],
["myFirstPTLab.htm","My First Packet Tracer 5.1 Lab","My First Packet Tracer 5.1 Lab Introduction Welcome to Packet Tracer 5.1. Research has shown that users who master a few basic tasks when first st...",""],
["operatingModes.htm","Operating Modes","Operating Modes Packet Tracer 5.1 operating modes reflect the network time scheme. In Realtime Mode, your network runs in a model of real time, wi...",""],
["search.html","Search","Search Enter keyword(s) to search. ",""],
["support.htm","Packet Tracer 5.1 Support and Contact Information","Packet Tracer 5.1 Support and Contact Information Please visit the Academy Connection website and its community forums for peer support. ",""],
["systemRequirements.htm","System Requirements","System Requirements Minimum CPU: Intel Pentium 300 MHz or equivalent OS: Microsoft Windows 2000, Microsoft Windows XP, Microsoft Windows Vista, Fe...",""],
["timeConstants.htm","Time Constants","Time Constants Packet Tracer 5.1 uses the following time constants: RIP/RIPv6 default update 30 secs RIP/RIPv6 default timeout 3 mins RIP/RIPv6 de...",""],
["tutorials.htm","Tutorials","Tutorials The following tutorials demonstrate the basic functions, features, and aspects of Packet Tracer 5.1. Although you can view them at any t...",""],
["tutorials_stub.htm","Tutorials","Tutorials The tutorial package is not installed. To view the tutorials, download the Packet Tracer tutorial package from Academy Connection and in...",""],
["usesForPT.htm","Uses for Packet Tracer 5.1","Uses for Packet Tracer 5.1 For Students Welcome to the world of computer networking. Packet Tracer 5.1 can be a fun, take-home, flexible piece of ...",""],
["whatsNew.htm","What&#39;s New","What&#39;s New Users of Packet Tracer 3.2 and 4.0 will note a variety of new features in Packet Tracer 5.1. Protocol Improvements Packet Tracer 5.1 mo...",""],
["workspaceBasics.htm","The Logical and Physical Workspaces","The Logical and Physical Workspaces Packet Tracer 5.1 uses two representation schemes for your network: the Logical Workspace and the Physical Wor...",""],
["workspace_logical.htm","The Logical Workspace","The Logical Workspace The Logical Workspace is where you will spend the majority of your time building and configuring your network. In conjunctio...",""],
["workspace_physical.htm","The Physical Workspace","The Physical Workspace The purpose of the Physical Workspace is to give a physical dimension to your logical network topology. It gives you a sens...",""],
["workspace_physical_movingDevices.htm","The Physical Workspace: Moving Devices","The Physical Workspace: Moving Devices The Physical Workspace allows you to move your devices to various locations. You will first need to create ...",""],
["workspace_physical_specialNotes.htm","The Physical Workspace: Special Notes","The Physical Workspace: Special Notes Using Custom Backgrounds The Physical Workspace comes with a default set of backgrounds (for the Intercity, ...",""],
["workspace_physical_Wireless.htm","The Physical Workspace: Wireless Devices","The Physical Workspace: Wireless Devices The Physical Workspace provides the dimension of distance to wireless devices. Access points can establis...",""]];
